---
- name: Install powerline
  pip:
    name: powerline-status
    extra_args: --user

- name: Downloading powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git 
    depth: 1
    dest: "~/fonts"
- name: Installing powerline fonts
  shell: /bin/sh install.sh
  args:
    chdir: "~/fonts/"

