set number
set ruler
set laststatus=2
set showcmd
set magic
set history=100
set showmatch
set ignorecase
set cursorline
let loaded_matchparen=1
set lazyredraw
set tabstop=4
set softtabstop=4
set expandtab
set hlsearch
set incsearch


set rtp+=/Users/shanker/Library/Python/2.7/lib/python/site-packages/powerline/bindings/vim
set laststatus=2
set t_Co=256

