---
# tasks file for ssh_config
- name: create ssh user directory
  file:
    path: "~/.ssh"
    state: directory
    mode: 0755

- name: copy ssh config
  copy:
    src: files/ssh/config
    dest: "~/.ssh/config"
    mode: 0644

